---
name: CanalQb GitHub Actions Demo
on:
  push: null
jobs:
  demo-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositÃ³rio
        uses: actions/checkout@v4
      - name: Mensagem inicial
        run: echo "ğŸ‰ OlÃ¡! Este job foi disparado pelo evento ${{ github.event_name }}."
      - name: Info do servidor
        run: echo "ğŸ§ Rodando em ${{ runner.os }} no GitHub."
      - name: Info do repositÃ³rio
        run: |
          echo "ğŸ” Branch: ${{ github.ref }} | Repo: ${{ github.repository }}"
      - name: Listar arquivos no workspace
        run: ls ${{ github.workspace }}
      - name: Mensagem final do CanalQb
        run: echo "ğŸš€ Obrigado por contribuir com o CanalQb! Visite
          https://www.youtube.com/@canalqb"
