name: Python package conda CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Miniconda (Miniforge3)
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniforge-variant: Miniforge3
          python-version: 3.8  # Usado s√≥ para setup
          channels: conda-forge,defaults
          auto-update-conda: true
          auto-activate-base: false

      - name: Create and activate environment from environment.yml 
        run: |
          conda env create --file environment.yml
          source $(conda info --base)/etc/profile.d/conda.sh
          conda activate teoremas
          python --version


      - name: Install additional dependencies (optional)
        run: |
          conda install --yes -n teoremas numpy pandas

      - name: Run tests with pytest
        run: |
          conda run -n teoremas pytest tests

      - name: Cache conda packages
        uses: actions/cache@v3
        with:
          path: ~/.conda/pkgs
          key: ${{ runner.os }}-conda-pkgs-${{ hashFiles('**/environment.yml') }}
          restore-keys: |
            ${{ runner.os }}-conda-pkgs-
